//! # vitepress.rs
//!
//! # VitePress 文档生成
//!
//! VitePress sidebar and support stats generation.
//! VitePress 侧边栏和支持级别统计生成。

use std::fmt::Write;

use super::doc_generator::{
    DocGeneratorConfig, get_builtin_support_level, get_effect_support_level,
};
use super::types::{BuiltinCategory, BuiltinDef, EffectDef, SupportLevel};

/// 支持级别统计 / Support level statistics
#[derive(Debug, Default)]
pub struct SupportStats {
    pub full_count: usize,
    pub partial_count: usize,
    pub unsupported_count: usize,
}

/// 获取支持级别的统计信息 / Get support level statistics
pub fn get_support_stats(effects: &[&EffectDef], config: &DocGeneratorConfig) -> SupportStats {
    let mut stats = SupportStats::default();

    for effect in effects {
        let support_level = get_effect_support_level(effect, config);

        match support_level {
            SupportLevel::Full => stats.full_count += 1,
            SupportLevel::Partial => stats.partial_count += 1,
            SupportLevel::Unsupported => stats.unsupported_count += 1,
        }
    }

    stats
}

/// 转换为 kebab-case / Convert to kebab-case
fn to_kebab_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('-');
            }
            result.push(c.to_ascii_lowercase());
        } else if c == '_' {
            result.push('-');
        } else {
            result.push(c);
        }
    }
    result
}

/// 生成 VitePress 效果侧边栏配置 / Generate VitePress effects sidebar config
pub fn generate_vitepress_effects_sidebar(effects: &[&EffectDef], lang: &str) -> String {
    let mut items = String::new();

    for (i, effect) in effects.iter().enumerate() {
        let name = if lang == "zh-hans" {
            effect.display_name_zh
        } else {
            effect.display_name_en
        };
        let link = format!("/{}/effects/{}", lang, to_kebab_case(effect.short_name));

        if i > 0 {
            items.push_str(",\n");
        }
        items.push_str(&format!(
            "                {{ text: '{}', link: '{}' }}",
            name, link
        ));
    }

    items
}

/// 生成 VitePress 侧边栏 TypeScript 模块（包含效果和内置功能）
/// Generate VitePress sidebar TypeScript module (including effects and builtins)
pub fn generate_vitepress_sidebar_snippet(
    effects: &[&EffectDef],
    builtins: &[&BuiltinDef],
    config: &DocGeneratorConfig,
) -> String {
    let mut output = String::new();

    writeln!(
        output,
        "// ⚠️ 此文件由 `cargo run --example generate_docs` 自动生成，请勿手动编辑。"
    )
    .unwrap();
    writeln!(output, "// ⚠️ This file is auto-generated by `cargo run --example generate_docs`. Do not edit manually.").unwrap();
    writeln!(output).unwrap();

    // 辅助函数：根据支持级别获取颜色标记
    // Helper function: get color indicator based on support level
    fn get_color_indicator(level: SupportLevel) -> &'static str {
        match level {
            // 使用非常淡的颜色 / Using very light colors
            // 绿色圆点表示完全支持 / Green dot for full support
            SupportLevel::Full => "<span style=\"color:#22c55e\">●</span> ",
            // 黄色圆点表示部分支持 / Yellow dot for partial support
            SupportLevel::Partial => "<span style=\"color:#eab308\">●</span> ",
            // 红色圆点表示不支持 / Red dot for unsupported
            SupportLevel::Unsupported => "<span style=\"color:#ef4444\">●</span> ",
        }
    }

    // 中文效果
    writeln!(output, "export const zhHansEffects = {{").unwrap();
    writeln!(output, "  text: '高级效果',").unwrap();
    writeln!(output, "  items: [").unwrap();
    for (i, effect) in effects.iter().enumerate() {
        let comma = if i < effects.len() - 1 { "," } else { "" };
        // 计算支持级别 / Calculate support level
        let support_level = get_effect_support_level(effect, config);
        let indicator = get_color_indicator(support_level);
        writeln!(
            output,
            "    {{ text: '{}{}', link: '/zh-hans/effects/{}' }}{}",
            indicator,
            effect.display_name_zh,
            to_kebab_case(effect.short_name),
            comma
        )
        .unwrap();
    }
    writeln!(output, "  ]").unwrap();
    writeln!(output, "}};").unwrap();
    writeln!(output).unwrap();

    // 英文效果
    writeln!(output, "export const enEffects = {{").unwrap();
    writeln!(output, "  text: 'Advanced Effects',").unwrap();
    writeln!(output, "  items: [").unwrap();
    for (i, effect) in effects.iter().enumerate() {
        let comma = if i < effects.len() - 1 { "," } else { "" };
        let support_level = get_effect_support_level(effect, config);
        let indicator = get_color_indicator(support_level);
        writeln!(
            output,
            "    {{ text: '{}{}', link: '/en/effects/{}' }}{}",
            indicator,
            effect.display_name_en,
            to_kebab_case(effect.short_name),
            comma
        )
        .unwrap();
    }
    writeln!(output, "  ]").unwrap();
    writeln!(output, "}};").unwrap();
    writeln!(output).unwrap();

    // 按分类分组内置功能 / Group builtins by category
    let categories = [
        BuiltinCategory::Properties,
        BuiltinCategory::Shapes,
        BuiltinCategory::Fill,
    ];

    // 中文内置功能 - 按分类分组
    writeln!(output, "export const zhHansBuiltins = [").unwrap();
    for (cat_idx, category) in categories.iter().enumerate() {
        let cat_builtins: Vec<_> = builtins
            .iter()
            .filter(|b| b.category == *category)
            .collect();
        if cat_builtins.is_empty() {
            continue;
        }

        let cat_comma = if cat_idx < categories.len() - 1 {
            ","
        } else {
            ""
        };
        writeln!(output, "  {{").unwrap();
        writeln!(output, "    text: '{}',", category.display_name_zh()).unwrap();
        writeln!(output, "    items: [").unwrap();
        for (i, builtin) in cat_builtins.iter().enumerate() {
            let comma = if i < cat_builtins.len() - 1 { "," } else { "" };
            let support_level = get_builtin_support_level(builtin, config);
            let indicator = get_color_indicator(support_level);
            writeln!(
                output,
                "      {{ text: '{}{}', link: '/zh-hans/builtins/{}' }}{}",
                indicator,
                builtin.display_name_zh,
                to_kebab_case(builtin.short_name),
                comma
            )
            .unwrap();
        }
        writeln!(output, "    ]").unwrap();
        writeln!(output, "  }}{}", cat_comma).unwrap();
    }
    writeln!(output, "];").unwrap();
    writeln!(output).unwrap();

    // 英文内置功能 - 按分类分组
    writeln!(output, "export const enBuiltins = [").unwrap();
    for (cat_idx, category) in categories.iter().enumerate() {
        let cat_builtins: Vec<_> = builtins
            .iter()
            .filter(|b| b.category == *category)
            .collect();
        if cat_builtins.is_empty() {
            continue;
        }

        let cat_comma = if cat_idx < categories.len() - 1 {
            ","
        } else {
            ""
        };
        writeln!(output, "  {{").unwrap();
        writeln!(output, "    text: '{}',", category.display_name_en()).unwrap();
        writeln!(output, "    items: [").unwrap();
        for (i, builtin) in cat_builtins.iter().enumerate() {
            let comma = if i < cat_builtins.len() - 1 { "," } else { "" };
            let support_level = get_builtin_support_level(builtin, config);
            let indicator = get_color_indicator(support_level);
            writeln!(
                output,
                "      {{ text: '{}{}', link: '/en/builtins/{}' }}{}",
                indicator,
                builtin.display_name_en,
                to_kebab_case(builtin.short_name),
                comma
            )
            .unwrap();
        }
        writeln!(output, "    ]").unwrap();
        writeln!(output, "  }}{}", cat_comma).unwrap();
    }
    writeln!(output, "];").unwrap();

    output
}
