# Default average and frame thresholds are both set to 0.98
#
# 默认的平均阀值和帧阀值均为0.98
[default]
avg_threshold = 0.98
frame_threshold = 0.95

# Known issues with Resolution Groups (AM export bug)
#
# 已知的分辨率组问题（AM导出错误）
[overrides.basic_resolution_group]
avg_threshold = 0.95
frame_threshold = 0.78

[overrides.basic_resolution_group_ex2]
avg_threshold = 0.90
frame_threshold = 0.70