// ⚠️ 此文件由 `cargo run --example generate_docs` 自动生成，请勿手动编辑。
// ⚠️ This file is auto-generated by `cargo run --example generate_docs`. Do not edit manually.

export const zhHansEffects = {
  text: '高级效果',
  items: [
    { text: '<span style="color:#eab308">●</span> 变换 (Transform2)', link: '/zh-hans/effects/transform2' },
    { text: '<span style="color:#22c55e">●</span> 擦拭 (Wipe2)', link: '/zh-hans/effects/wipe2' },
    { text: '<span style="color:#22c55e">●</span> 拉伸片段 (Stretch Segment)', link: '/zh-hans/effects/stretch-segment' },
    { text: '<span style="color:#eab308">●</span> 拉伸 (Stretch)', link: '/zh-hans/effects/stretch2' },
    { text: '<span style="color:#ef4444">●</span> 高斯模糊 (Gaussian Blur)', link: '/zh-hans/effects/gaussian-blur' },
    { text: '<span style="color:#22c55e">●</span> 网格 (Grid)', link: '/zh-hans/effects/grid' },
    { text: '<span style="color:#eab308">●</span> 阈值 (Threshold)', link: '/zh-hans/effects/threshold' },
    { text: '<span style="color:#eab308">●</span> 调色板映射 (Palette Map)', link: '/zh-hans/effects/palette-map' },
    { text: '<span style="color:#22c55e">●</span> 颜色替换 (Replace Color)', link: '/zh-hans/effects/replace-color' },
    { text: '<span style="color:#22c55e">●</span> 缩放辅助 (Scale Assist)', link: '/zh-hans/effects/scale-assist' },
    { text: '<span style="color:#eab308">●</span> 像素化 (Pixelate)', link: '/zh-hans/effects/pixelate' },
    { text: '<span style="color:#eab308">●</span> 振荡 (Oscillate)', link: '/zh-hans/effects/oscillate3' },
    { text: '<span style="color:#22c55e">●</span> 抖动 (Jitter)', link: '/zh-hans/effects/jitter' },
    { text: '<span style="color:#eab308">●</span> 重复 (Repeat)', link: '/zh-hans/effects/repeat' },
    { text: '<span style="color:#eab308">●</span> 线性重复 (Linear Repeat)', link: '/zh-hans/effects/linear-repeat' },
    { text: '<span style="color:#22c55e">●</span> 径向重复 (Radial Repeat)', link: '/zh-hans/effects/radial-repeat' },
    { text: '<span style="color:#22c55e">●</span> 路径重复 (Path Repeat)', link: '/zh-hans/effects/path-repeat' },
    { text: '<span style="color:#22c55e">●</span> 回声关键帧 (Echo Keyframes)', link: '/zh-hans/effects/echokf' },
    { text: '<span style="color:#eab308">●</span> 纯色 (Solid Color)', link: '/zh-hans/effects/solidcolor' },
    { text: '<span style="color:#ef4444">●</span> 摇摆 (Swing)', link: '/zh-hans/effects/swing2' },
    { text: '<span style="color:#22c55e">●</span> 旋转 (Spin)', link: '/zh-hans/effects/spin' },
    { text: '<span style="color:#ef4444">●</span> 文字进度 (Text Progress)', link: '/zh-hans/effects/textprogress' },
    { text: '<span style="color:#ef4444">●</span> 文字间距 (Text Spacing)', link: '/zh-hans/effects/textspacing' }
  ]
};

export const enEffects = {
  text: 'Advanced Effects',
  items: [
    { text: '<span style="color:#eab308">●</span> Transform2', link: '/en/effects/transform2' },
    { text: '<span style="color:#22c55e">●</span> Wipe2', link: '/en/effects/wipe2' },
    { text: '<span style="color:#22c55e">●</span> Stretch Segment', link: '/en/effects/stretch-segment' },
    { text: '<span style="color:#eab308">●</span> Stretch', link: '/en/effects/stretch2' },
    { text: '<span style="color:#ef4444">●</span> Gaussian Blur', link: '/en/effects/gaussian-blur' },
    { text: '<span style="color:#22c55e">●</span> Grid', link: '/en/effects/grid' },
    { text: '<span style="color:#eab308">●</span> Threshold', link: '/en/effects/threshold' },
    { text: '<span style="color:#eab308">●</span> Palette Map', link: '/en/effects/palette-map' },
    { text: '<span style="color:#22c55e">●</span> Replace Color', link: '/en/effects/replace-color' },
    { text: '<span style="color:#22c55e">●</span> Scale Assist', link: '/en/effects/scale-assist' },
    { text: '<span style="color:#eab308">●</span> Pixelate', link: '/en/effects/pixelate' },
    { text: '<span style="color:#eab308">●</span> Oscillate', link: '/en/effects/oscillate3' },
    { text: '<span style="color:#22c55e">●</span> Jitter', link: '/en/effects/jitter' },
    { text: '<span style="color:#eab308">●</span> Repeat', link: '/en/effects/repeat' },
    { text: '<span style="color:#eab308">●</span> Linear Repeat', link: '/en/effects/linear-repeat' },
    { text: '<span style="color:#22c55e">●</span> Radial Repeat', link: '/en/effects/radial-repeat' },
    { text: '<span style="color:#22c55e">●</span> Path Repeat', link: '/en/effects/path-repeat' },
    { text: '<span style="color:#22c55e">●</span> Echo Keyframes', link: '/en/effects/echokf' },
    { text: '<span style="color:#eab308">●</span> Solid Color', link: '/en/effects/solidcolor' },
    { text: '<span style="color:#ef4444">●</span> Swing', link: '/en/effects/swing2' },
    { text: '<span style="color:#22c55e">●</span> Spin', link: '/en/effects/spin' },
    { text: '<span style="color:#ef4444">●</span> Text Progress', link: '/en/effects/textprogress' },
    { text: '<span style="color:#ef4444">●</span> Text Spacing', link: '/en/effects/textspacing' }
  ]
};

export const zhHansBuiltins = [
  {
    text: '基本属性',
    items: [
      { text: '<span style="color:#22c55e">●</span> 描边', link: '/zh-hans/builtins/stroke' },
      { text: '<span style="color:#22c55e">●</span> 变换', link: '/zh-hans/builtins/transform' }
    ]
  },
  {
    text: '基本形状',
    items: [
      { text: '<span style="color:#22c55e">●</span> 矩形', link: '/zh-hans/builtins/rect' },
      { text: '<span style="color:#22c55e">●</span> 圆形', link: '/zh-hans/builtins/circle' },
      { text: '<span style="color:#22c55e">●</span> 圆角矩形', link: '/zh-hans/builtins/roundrect' },
      { text: '<span style="color:#22c55e">●</span> 三角形', link: '/zh-hans/builtins/triangle' },
      { text: '<span style="color:#22c55e">●</span> 星形', link: '/zh-hans/builtins/star' },
      { text: '<span style="color:#22c55e">●</span> 多边形', link: '/zh-hans/builtins/poly' },
      { text: '<span style="color:#22c55e">●</span> 菱形', link: '/zh-hans/builtins/quad' },
      { text: '<span style="color:#22c55e">●</span> 五边形', link: '/zh-hans/builtins/penta' },
      { text: '<span style="color:#22c55e">●</span> 扇形', link: '/zh-hans/builtins/pie' },
      { text: '<span style="color:#22c55e">●</span> 十字形', link: '/zh-hans/builtins/plus' },
      { text: '<span style="color:#22c55e">●</span> 多叶形', link: '/zh-hans/builtins/multifoil' },
      { text: '<span style="color:#22c55e">●</span> 弧形', link: '/zh-hans/builtins/arc' },
      { text: '<span style="color:#22c55e">●</span> 线段', link: '/zh-hans/builtins/line' },
      { text: '<span style="color:#22c55e">●</span> 正 N 边形', link: '/zh-hans/builtins/ngon' }
    ]
  },
  {
    text: '填充',
    items: [
      { text: '<span style="color:#22c55e">●</span> 颜色填充', link: '/zh-hans/builtins/color-fill' },
      { text: '<span style="color:#22c55e">●</span> 媒体填充', link: '/zh-hans/builtins/media-fill' }
    ]
  }
];

export const enBuiltins = [
  {
    text: 'Properties',
    items: [
      { text: '<span style="color:#22c55e">●</span> Stroke', link: '/en/builtins/stroke' },
      { text: '<span style="color:#22c55e">●</span> Transform', link: '/en/builtins/transform' }
    ]
  },
  {
    text: 'Basic Shapes',
    items: [
      { text: '<span style="color:#22c55e">●</span> Rectangle', link: '/en/builtins/rect' },
      { text: '<span style="color:#22c55e">●</span> Circle', link: '/en/builtins/circle' },
      { text: '<span style="color:#22c55e">●</span> Rounded Rectangle', link: '/en/builtins/roundrect' },
      { text: '<span style="color:#22c55e">●</span> Triangle', link: '/en/builtins/triangle' },
      { text: '<span style="color:#22c55e">●</span> Star', link: '/en/builtins/star' },
      { text: '<span style="color:#22c55e">●</span> Polygon', link: '/en/builtins/poly' },
      { text: '<span style="color:#22c55e">●</span> Quad', link: '/en/builtins/quad' },
      { text: '<span style="color:#22c55e">●</span> Pentagon', link: '/en/builtins/penta' },
      { text: '<span style="color:#22c55e">●</span> Pie', link: '/en/builtins/pie' },
      { text: '<span style="color:#22c55e">●</span> Plus', link: '/en/builtins/plus' },
      { text: '<span style="color:#22c55e">●</span> Multifoil', link: '/en/builtins/multifoil' },
      { text: '<span style="color:#22c55e">●</span> Arc', link: '/en/builtins/arc' },
      { text: '<span style="color:#22c55e">●</span> Line', link: '/en/builtins/line' },
      { text: '<span style="color:#22c55e">●</span> N-gon', link: '/en/builtins/ngon' }
    ]
  },
  {
    text: 'Fills',
    items: [
      { text: '<span style="color:#22c55e">●</span> Color Fill', link: '/en/builtins/color-fill' },
      { text: '<span style="color:#22c55e">●</span> Media Fill', link: '/en/builtins/media-fill' }
    ]
  }
];
