// ⚠️ 此文件由 `cargo run --example generate_docs` 自动生成，请勿手动编辑。
// ⚠️ This file is auto-generated by `cargo run --example generate_docs`. Do not edit manually.

export const zhHansEffects = {
  text: '高级效果',
  items: [
    { text: '<span style="color:#eab308">●</span> 变换 (Transform2)', link: '/zh-hans/effects/transform2' },
    { text: '<span style="color:#22c55e">●</span> 擦拭 (Wipe2)', link: '/zh-hans/effects/wipe2' },
    { text: '<span style="color:#ef4444">●</span> 拉伸片段 (Stretch Segment)', link: '/zh-hans/effects/stretch-segment' },
    { text: '<span style="color:#ef4444">●</span> 高斯模糊 (Gaussian Blur)', link: '/zh-hans/effects/gaussian-blur' },
    { text: '<span style="color:#ef4444">●</span> 调色板映射 (Palette Map)', link: '/zh-hans/effects/palette-map' },
    { text: '<span style="color:#ef4444">●</span> 颜色替换 (Replace Color)', link: '/zh-hans/effects/replace-color' },
    { text: '<span style="color:#ef4444">●</span> 缩放辅助 (Scale Assist)', link: '/zh-hans/effects/scale-assist' },
    { text: '<span style="color:#ef4444">●</span> 重复 (Repeat)', link: '/zh-hans/effects/repeat' },
    { text: '<span style="color:#22c55e">●</span> 线性重复 (Linear Repeat)', link: '/zh-hans/effects/linear-repeat' }
  ]
};

export const enEffects = {
  text: 'Advanced Effects',
  items: [
    { text: '<span style="color:#eab308">●</span> Transform2', link: '/en/effects/transform2' },
    { text: '<span style="color:#22c55e">●</span> Wipe2', link: '/en/effects/wipe2' },
    { text: '<span style="color:#ef4444">●</span> Stretch Segment', link: '/en/effects/stretch-segment' },
    { text: '<span style="color:#ef4444">●</span> Gaussian Blur', link: '/en/effects/gaussian-blur' },
    { text: '<span style="color:#ef4444">●</span> Palette Map', link: '/en/effects/palette-map' },
    { text: '<span style="color:#ef4444">●</span> Replace Color', link: '/en/effects/replace-color' },
    { text: '<span style="color:#ef4444">●</span> Scale Assist', link: '/en/effects/scale-assist' },
    { text: '<span style="color:#ef4444">●</span> Repeat', link: '/en/effects/repeat' },
    { text: '<span style="color:#22c55e">●</span> Linear Repeat', link: '/en/effects/linear-repeat' }
  ]
};

export const zhHansBuiltins = [
  {
    text: '基本属性',
    items: [
      { text: '<span style="color:#ef4444">●</span> 描边', link: '/zh-hans/builtins/stroke' },
      { text: '<span style="color:#ef4444">●</span> 变换', link: '/zh-hans/builtins/transform' }
    ]
  },
  {
    text: '基本形状',
    items: [
      { text: '<span style="color:#ef4444">●</span> 矩形', link: '/zh-hans/builtins/rect' },
      { text: '<span style="color:#ef4444">●</span> 圆形', link: '/zh-hans/builtins/circle' }
    ]
  },
  {
    text: '填充',
    items: [
      { text: '<span style="color:#ef4444">●</span> 颜色填充', link: '/zh-hans/builtins/color-fill' },
      { text: '<span style="color:#ef4444">●</span> 媒体填充', link: '/zh-hans/builtins/media-fill' }
    ]
  }
];

export const enBuiltins = [
  {
    text: 'Properties',
    items: [
      { text: '<span style="color:#ef4444">●</span> Stroke', link: '/en/builtins/stroke' },
      { text: '<span style="color:#ef4444">●</span> Transform', link: '/en/builtins/transform' }
    ]
  },
  {
    text: 'Basic Shapes',
    items: [
      { text: '<span style="color:#ef4444">●</span> Rectangle', link: '/en/builtins/rect' },
      { text: '<span style="color:#ef4444">●</span> Circle', link: '/en/builtins/circle' }
    ]
  },
  {
    text: 'Fills',
    items: [
      { text: '<span style="color:#ef4444">●</span> Color Fill', link: '/en/builtins/color-fill' },
      { text: '<span style="color:#ef4444">●</span> Media Fill', link: '/en/builtins/media-fill' }
    ]
  }
];
