//! # collect_embed.rs
//!
//! # 嵌入场景收集
//!
//! Functions for collecting embed scene layer data into PendingLayer.
//! 嵌入场景图层数据收集为 PendingLayer 的函数。

mod base;
mod group_fill;

use bevy::prelude::*;
use std::collections::HashMap;

use crate::animation::AmAnimated;
use crate::loader::FontMetrics;
use crate::schema::{AmAnimatedFloat, AmAnimatedVec2};

use self::base::collect_embed_base;
use self::group_fill::build_group_fill;
use super::components::*;
use super::effects::*;
use super::helpers::get_base_alpha;

/// Collect an embed scene's data recursively.
pub(crate) fn collect_embed_scene(
    embed: &crate::schema::AmEmbedScene,
    fonts: &HashMap<String, Handle<Font>>,
    font_metrics: &HashMap<String, FontMetrics>,
    config: &AmSceneConfig,
    z: f32,
) -> PendingLayer {
    let base = collect_embed_base(embed, fonts, font_metrics, config, z);
    let group_fill = build_group_fill(embed);

    let mut all_embed_transform2 = extract_all_transform2_effects(&embed.effects);
    let embed_transform2 = if all_embed_transform2.is_empty() {
        Transform2Params::default()
    } else {
        all_embed_transform2.remove(0)
    };
    let embed_extra_transform2 = all_embed_transform2;

    let jitter_effect = extract_jitter_effect(&embed.effects);
    let sd_effect = extract_simplex_displace_effect(&embed.effects);
    let rgb_split_effect = extract_rgb_split_effect(&embed.effects);
    let fade_effect = extract_fade_effect(&embed.effects);
    let wavewarp2_effect = extract_wavewarp2_effect(&embed.effects);
    let mirror_effect = extract_mirror_effect(&embed.effects);
    let lift_effect = extract_lift_effect(&embed.effects);
    let rays_effect = extract_rays_effect(&embed.effects);
    let exposure_gamma_effect = extract_exposure_gamma_effect(&embed.effects);
    let chromakey_effect = extract_chromakey_effect(&embed.effects);
    let replace_color = extract_replace_color_effect(&embed.effects);

    PendingLayer {
        id: embed.id,
        label: embed.label.clone(),
        parent: embed.parent,
        start_time: embed.start_time,
        end_time: embed.end_time,
        transform: base.transform,
        animated: AmAnimated {
            layer_id: embed.id,
            start_time: embed.start_time,
            end_time: embed.end_time,
            time_offset: config.time_offset,
            lifecycle_offset: config.lifecycle_offset,
            location: embed.transform.location.clone(),
            pivot: embed.transform.pivot.clone(),
            rotation: embed.transform.rotation.clone(),
            scale: embed.transform.scale.clone(),
            opacity: embed.transform.opacity.clone(),
            canvas_width: config.canvas_width,
            canvas_height: config.canvas_height,
            has_parent: base.has_parent,
            parent_layer_id: embed.parent,
            effect_pos_x: embed_transform2.pos_x,
            effect_pos_y: embed_transform2.pos_y,
            effect_posz: embed_transform2.pos_z,
            effect_angle: embed_transform2.angle,
            effect_xinv: embed_transform2.xinv,
            effect_yinv: embed_transform2.yinv,
            effect_zinv: embed_transform2.zinv,
            effect_ainv: embed_transform2.ainv,
            extra_transform2: embed_extra_transform2,
            font_y_offset: 0.0,
            size: AmAnimatedVec2::default(),
            anchor_offset: Vec2::ZERO,
            wipe_start: AmAnimatedFloat::default(),
            wipe_end: AmAnimatedFloat {
                value: Some(1.0),
                keyframes: vec![],
            },
            wipe_angle: AmAnimatedFloat::default(),
            wipe_feather: AmAnimatedFloat::default(),
            stretch_angle: AmAnimatedFloat::default(),
            stretch_amount: AmAnimatedFloat::default(),
            stretch_offset: AmAnimatedFloat::default(),
            stretch_smooth: AmAnimatedFloat::default(),
            stretch_seg2_angle: AmAnimatedFloat::default(),
            stretch_seg2_amount: AmAnimatedFloat::default(),
            stretch_seg2_offset: AmAnimatedFloat::default(),
            stretch_seg2_smooth: AmAnimatedFloat::default(),
            blur_strength: AmAnimatedFloat::default(),
            speed_multiplier: config.speed_multiplier,
            element_speed: 1.0,
            scene_fps: config.scene_fps,
            embed_offset: Vec2::ZERO,
            inv_fit_scale: 1.0,
            stroke_width: AmAnimatedFloat::default(),
            base_alpha: get_base_alpha(&embed.fill_color, false) * config.repeat_alpha_factor,
            fade_in_time: fade_effect.in_time,
            fade_out_time: fade_effect.out_time,
            fade_layer_duration_ms: (embed.end_time - embed.start_time) as f32,
            palette_alpha: AmAnimatedFloat::default(),
            scale_assist: AmAnimatedFloat::default(),
            scale_assist_damp: AmAnimatedFloat::default(),
            scale_assist_axis: 0,
            parenthelper_scale_mode: 0,
            parenthelper_rotate_mode: 0,
            parenthelper_scale_weight: AmAnimatedFloat::default(),
            parenthelper_rotate_weight: AmAnimatedFloat::default(),
            parenthelper_auto_rotate: 0,
            parenthelper_radius_adjust: AmAnimatedFloat::default(),
            parenthelper_has_effect: false,
            stretch2_scale: AmAnimatedFloat::default(),
            stretch2_angle: AmAnimatedFloat::default(),
            stretch2_content_only: false,
            wavewarp2_phase: wavewarp2_effect.phase,
            wavewarp2_a1d: wavewarp2_effect.a1d,
            wavewarp2_m1: wavewarp2_effect.m1,
            wavewarp2_m2: wavewarp2_effect.m2,
            wavewarp2_a2d: wavewarp2_effect.a2d,
            wavewarp2_damping: wavewarp2_effect.damping,
            wavewarp2_damping_space: wavewarp2_effect.damping_space,
            wavewarp2_damping_origin: wavewarp2_effect.damping_origin,
            wavewarp2_screen_space: wavewarp2_effect.screen_space,
            wavewarp2_has_effect: wavewarp2_effect.has_effect,
            mirror_type: mirror_effect.mirror_type,
            mirror_blend_mode: mirror_effect.blend_mode,
            mirror_alpha: mirror_effect.alpha,
            mirror_offset: mirror_effect.offset,
            mirror_has_effect: mirror_effect.has_effect,
            lift_fill: lift_effect.fill,
            lift_has_effect: lift_effect.has_effect,
            rays_center_x: rays_effect.center_x,
            rays_center_y: rays_effect.center_y,
            rays_strength: rays_effect.strength,
            rays_intensity: rays_effect.intensity,
            rays_threshold: rays_effect.threshold,
            rays_threshold_color: rays_effect.threshold_color,
            rays_fill_color: rays_effect.fill_color,
            rays_blend: rays_effect.blend,
            rays_quality: rays_effect.quality,
            rays_has_effect: rays_effect.has_effect,
            replace_old_color: replace_color.old_color,
            replace_new_color: replace_color.new_color,
            replace_threshold: replace_color.threshold,
            replace_feather: replace_color.feather,
            replace_alpha: replace_color.alpha,
            replace_lock_luminance: replace_color.lock_luminance,
            repeat_count: AmAnimatedFloat::default(),
            repeat_offset: AmAnimatedVec2::default(),
            repeat_angle: AmAnimatedFloat::default(),
            repeat_scale: AmAnimatedFloat::default(),
            repeat_alpha: AmAnimatedFloat::default(),
            linear_repeat_count: AmAnimatedFloat::default(),
            linear_repeat_position: AmAnimatedVec2::default(),
            linear_repeat_offset: AmAnimatedVec2::default(),
            linear_repeat_angle: AmAnimatedFloat::default(),
            linear_repeat_scale: AmAnimatedFloat {
                value: Some(1.0),
                keyframes: vec![],
            },
            linear_repeat_alpha: AmAnimatedFloat {
                value: Some(1.0),
                keyframes: vec![],
            },
            linear_repeat_fill_color: crate::schema::AmAnimatedColor::default(),
            linear_repeat_blend: AmAnimatedFloat::default(),
            linear_repeat_color_alt_copies: false,
            linear_repeat_start: AmAnimatedFloat::default(),
            linear_repeat_end: AmAnimatedFloat {
                value: Some(1.0),
                keyframes: vec![],
            },
            linear_repeat_phase: AmAnimatedFloat::default(),
            linear_repeat_ease_in: AmAnimatedFloat::default(),
            linear_repeat_ease_out: AmAnimatedFloat::default(),
            linear_repeat_overlap: AmAnimatedFloat::default(),
            linear_repeat_shape: 0,
            linear_repeat_invert: false,
            linear_repeat_random_order: false,
            linear_repeat_seed: AmAnimatedFloat::default(),
            linear_repeat2: None,
            radial_repeat_count: AmAnimatedFloat::default(),
            radial_repeat_radius: AmAnimatedFloat::default(),
            radial_repeat_orientation: AmAnimatedFloat::default(),
            radial_repeat_start_angle: AmAnimatedFloat::default(),
            radial_repeat_sweep: AmAnimatedFloat::default(),
            radial_repeat_base_scale: AmAnimatedFloat::default(),
            radial_repeat_offset: AmAnimatedVec2::default(),
            radial_repeat_angle: AmAnimatedFloat::default(),
            radial_repeat_scale: AmAnimatedFloat::default(),
            radial_repeat_alpha: AmAnimatedFloat::default(),
            radial_repeat_fill_color: crate::schema::AmAnimatedColor::default(),
            radial_repeat_blend: AmAnimatedFloat::default(),
            radial_repeat_color_alt_copies: false,
            radial_repeat_start: AmAnimatedFloat::default(),
            radial_repeat_end: AmAnimatedFloat {
                value: Some(1.0),
                ..Default::default()
            },
            radial_repeat_phase: AmAnimatedFloat::default(),
            radial_repeat_ease_in: AmAnimatedFloat::default(),
            radial_repeat_ease_out: AmAnimatedFloat::default(),
            radial_repeat_overlap: AmAnimatedFloat::default(),
            radial_repeat_shape: 0,
            radial_repeat_invert: false,
            radial_repeat_random_order: false,
            radial_repeat_seed: 0.0,
            swing_freq: AmAnimatedFloat::default(),
            swing_a1: AmAnimatedFloat::default(),
            swing_a2: AmAnimatedFloat::default(),
            swing_phase: AmAnimatedFloat::default(),
            swing_type: 0,
            oscillate_direction: 0,
            oscillate_angle: AmAnimatedFloat::default(),
            oscillate_freq: AmAnimatedFloat::default(),
            oscillate_mag: AmAnimatedFloat::default(),
            oscillate_wave_type: 0,
            oscillate_phase: AmAnimatedFloat::default(),
            spin_rpm: AmAnimatedFloat::default(),
            threshold_value: AmAnimatedFloat::default(),
            threshold_feather: AmAnimatedFloat::default(),
            threshold_invert: false,
            threshold_blend_mode: 0,
            grid_position: AmAnimatedVec2::default(),
            grid_spacing: AmAnimatedFloat::default(),
            grid_width: AmAnimatedFloat::default(),
            grid_color: crate::schema::AmAnimatedColor::default(),
            grid_punchout: false,
            grid_smoothing: AmAnimatedFloat::default(),
            grid_screen_space: false,
            pixelate_size: AmAnimatedFloat::default(),
            pixelate_stretch: AmAnimatedVec2::default(),
            pixelate_angle: AmAnimatedFloat::default(),
            pixelate_vignette: AmAnimatedFloat::default(),
            pixelate_threshold: AmAnimatedFloat::default(),
            pixelate_saturation: AmAnimatedFloat::default(),
            pixelate_screen_space: false,
            solid_color: Default::default(),
            solid_color_alpha: Default::default(),
            solid_color_blend_mode: 0,
            base_fill_color: [0.0; 4],
            fill_color: Default::default(),
            path_repeat: None,
            textspacing_letter: Default::default(),
            textspacing_line: AmAnimatedFloat {
                value: Some(1.0),
                keyframes: vec![],
            },
            textprogress_start: Default::default(),
            textprogress_end: AmAnimatedFloat {
                value: Some(1.0),
                keyframes: vec![],
            },
            textprogress_cursor: 0,
            textprogress_blink: false,
            counter_offset: AmAnimatedFloat::default(),
            counter_scale: AmAnimatedFloat::default(),
            shape_props: Default::default(),
            shape_points: Default::default(),
            jitter_enabled: jitter_effect.enabled,
            jitter_angle: jitter_effect.angle,
            jitter_freq: jitter_effect.freq,
            jitter_mag: jitter_effect.mag,
            jitter_seed: jitter_effect.seed,
            jitter_slack: jitter_effect.slack,
            jitter_zjitter: jitter_effect.zjitter,
            sd_enabled: sd_effect.enabled,
            sd_mag: sd_effect.mag,
            sd_evolution: sd_effect.evolution,
            sd_seed: sd_effect.seed,
            sd_scatter: sd_effect.scatter,
            rgb_split_enabled: rgb_split_effect.enabled,
            rgb_split_strength: rgb_split_effect.strength,
            rgb_split_angle: rgb_split_effect.angle,
            rgb_split_center: rgb_split_effect.center_channel,
            rgb_split_mode: rgb_split_effect.mode,
            exposure_value: exposure_gamma_effect.exposure,
            exposure_gamma: exposure_gamma_effect.gamma,
            exposure_offset: exposure_gamma_effect.offset,
            exposure_has_effect: exposure_gamma_effect.has_effect,
            chromakey_enabled: chromakey_effect.enabled,
            chromakey_key_color: chromakey_effect.key_color,
            chromakey_threshold: chromakey_effect.threshold,
            chromakey_feather: chromakey_effect.feather,
            chromakey_defringe: chromakey_effect.defringe,
            chromakey_invert: chromakey_effect.invert,
            blend_mode: AmBlendingMode::default(),
            retime: config.retime.clone(),
            echo_time_shift_ms: config.echo_time_shift_ms,
            echo_alpha_config: config.echo_alpha_config.clone(),
            repeat_rotation_offset_deg: -config.repeat_rotation_deg,
            repeat_scale_factor: config.repeat_scale_factor,
            repeat_position_offset: config.repeat_offset,
            embed_inner_total_time: None,
        },
        spec: AmLayerSpec::EmbedScene,
        z_index: z,
        children: base.children,
        blending_mode: AmBlendingMode::parse_am(embed.blending.as_str()),
        mask_info: None,
        palette_params: None,
        embed_scene_size: Some((embed.scene.width as f32, embed.scene.height as f32)),
        containing_embed_id: 0,
        from_deeply_nested_scene: config.nesting_depth > 1,
        echo_runtime: None,
        group_fill,
        embed_requires_composite: embed.fill_type == "intrinsic",
        embed_dynamic_resolution: embed.scene.precompose == "dynamicResolution",
        embed_inner_total_time: None,
        hidden: embed.hidden,
    }
}
